{{ if .Values.kubeconfig_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helpers.fullname" . }}-kubeconfig
stringData: 
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: {{ .Values.cluster_url }}
      name: {{ .Values.cluster }}
    contexts:
    - context:
        cluster: {{ .Values.cluster }}
        user: {{ .Values.cluster_user }}
      name: {{ .Values.cluster }}
    current-context: {{ .Values.cluster }}
    preferences: {}
    users:
    - name: {{ .Values.cluster_user }}
      user:
        token: {{ .Values.kubeconfig_token }}
{{ end }}
